spring:
  application:
    name: admin-server
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://34.118.226.218:8888}

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://34.135.127.54:8761/
